image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

before_script:
  - apk add --no-cache make go

build:
  stage: build
  script:
    - docker build -t ginger-api:latest .

test-int:
  stage: test
  script:
    - docker compose -f docker-compose.yml up -d psql_test
    - sleep 5
    - make test-int
