version: '3'

services:
  psql:
    image: postgres:13
    container_name: psql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/ #-this is not working???
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - ginger-network

  psql_test:
    image: postgres:13
    container_name: psql_test_db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d/
    ports:
      - "6432:5432"
    expose:
      - 6432
    networks:
      - ginger-network
    
  ginger-api:
    image: ginger-api:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=psql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - psql
    networks:
      - ginger-network

networks:
  ginger-network:
    driver: bridge

volumes:
  pg_data:
