version: '3'

services:
  psql:
    image: postgres:13
    container_name: psql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/ #-this is not working???
    ports:
      - "5388:5432"
    expose:
      - 5388
    networks:
      - ginger-network

  psql_test:
    image: postgres:13
    container_name: psql_test_db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d/
    ports:
      - "6432:5432"
    expose:
      - 6432
    networks:
      - ginger-network
networks:
  ginger-network:
    driver: bridge

volumes:
  pg_data:
