apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: ginger-api
  name: ginger-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ginger-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: ginger-api
    spec:
      containers:
        - name: ginger-api
          image: ginger-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@psql:5432/postgres?sslmode=disable
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      restartPolicy: Always
